### ISSUE TITLE
Application.selectLang should be a UserAwareAction, not InsecureAction

### ISSUE THREAD

**Issue by ehudkaldor** [adrianhurt/play-silhouette-credentials-seed#4]
with InsecureAction, if a user is already logged in and changes language, they get "unauthorized" response as the redirection in Application.selectLang seems to ignore the fact they are already logged in. changing is to UserAwareAction got the right effect: when logged in, clicking the language simply re-rendered the page in the selected language.

**Comment by adrianhurt** [comment]
You're totally right. Thanks!
