### ISSUE TITLE
Deep link into the application

### ISSUE THREAD

**Issue by nemoo** [adrianhurt/play-silhouette-credentials-seed#6]
First of all, I love this seed, it is very helpfull!

When I deep link into a web application that is not a single page app and I have just submitted my correct credentials, I would expect to land on the page that the deep link described , not always on the index page.

This is pretty important if a deep link looks like this: 
https://example.com/cars/893

Then the user would have to search for car 893 again within the app because the information from his deep link has been ignored.

I think that feature should be added to this example. How could this be done?

**Comment by adrianhurt** [comment]
Hi @nemoo, you can try with referer attribute or maybe with your own session variables. For example, something like:

```
request.headers.get(REFERER).map { referer =>
  Redirect(referer)
}.getOrElse {
  Redirect(routes.Application.index)
}
```

**Comment by nemoo** [comment]
The referer attribute did not work because it refers to http://localhost:9000/signin

But it worked nicely with a session variable. 
Works now as expected. 
I opened a pull request for the implementation, it is ready to be merged.

**Comment by adrianhurt** [comment]
Thanks for the PR
